name: owner
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.5.2
  get: ^4.7.1
  flutter_skeleton_ui: ^0.0.6
  image_picker: ^1.1.2
  syncfusion_flutter_calendar: ^28.2.5
  jiffy: ^6.3.2
  connectivity_plus: ^6.1.3
  syncfusion_flutter_charts: ^28.2.5+1
  flutter_widget_from_html: ^0.15.3
  flutter_otp_text_field: ^1.4.0+2
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  country_picker: ^2.0.27
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
