// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZTHDS-xVZgkCc9-5g0OQ7EqvZWYKkxYw',
    appId: '1:459600208813:web:81059d5fd8fc0b67e07724',
    messagingSenderId: '459600208813',
    projectId: 'thai-massage-8a4e7',
    authDomain: 'thai-massage-8a4e7.firebaseapp.com',
    storageBucket: 'thai-massage-8a4e7.firebasestorage.app',
    measurementId: 'G-9P6T15CFVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZGsg9ytjUCFMN9cQ5cxE614Lx6YSqNaM',
    appId: '1:459600208813:android:e7ad8222b569b3b4e07724',
    messagingSenderId: '459600208813',
    projectId: 'thai-massage-8a4e7',
    storageBucket: 'thai-massage-8a4e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbzfbwBavB68K1wrbTm-8TiSdPiVU3pcI',
    appId: '1:459600208813:ios:18453fcb0db0f736e07724',
    messagingSenderId: '459600208813',
    projectId: 'thai-massage-8a4e7',
    storageBucket: 'thai-massage-8a4e7.firebasestorage.app',
    iosBundleId: 'io.initappz.ultimate.salon.owner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbzfbwBavB68K1wrbTm-8TiSdPiVU3pcI',
    appId: '1:459600208813:ios:18453fcb0db0f736e07724',
    messagingSenderId: '459600208813',
    projectId: 'thai-massage-8a4e7',
    storageBucket: 'thai-massage-8a4e7.firebasestorage.app',
    iosBundleId: 'io.initappz.ultimate.salon.owner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZTHDS-xVZgkCc9-5g0OQ7EqvZWYKkxYw',
    appId: '1:459600208813:web:dc4f63b6cd2533aae07724',
    messagingSenderId: '459600208813',
    projectId: 'thai-massage-8a4e7',
    authDomain: 'thai-massage-8a4e7.firebaseapp.com',
    storageBucket: 'thai-massage-8a4e7.firebasestorage.app',
    measurementId: 'G-RR4N891G54',
  );

}